name: ND_north_star
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_5
  - ca-certificates=2024.3.11=haa95532_0
  - expat=2.5.0=hd77b12b_0
  - libffi=3.4.4=hd77b12b_0
  - openssl=3.0.13=h2bbff1b_0
  - pip=23.3.1=py312haa95532_0
  - python=3.12.2=h1d929f7_0
  - setuptools=68.2.2=py312haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - tzdata=2024a=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.41.2=py312haa95532_0
  - xz=5.4.6=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
      - asttokens==2.4.1
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - executing==2.0.1
      - fonttools==4.51.0
      - ipykernel==6.29.4
      - ipython==8.23.0
      - jedi==0.19.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - kiwisolver==1.4.5
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - nest-asyncio==1.6.0
      - numpy==1.26.4
      - packaging==24.0
      - parso==0.8.4
      - perlin-noise==1.12
      - pillow==10.3.0
      - platformdirs==4.2.0
      - prompt-toolkit==3.0.43
      - psutil==5.9.8
      - pure-eval==0.2.2
      - pydoe2==1.3.0
      - pygments==2.17.2
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pywin32==306
      - pyzmq==26.0.0
      - scipy==1.13.0
      - six==1.16.0
      - stack-data==0.6.3
      - tornado==6.4
      - traitlets==5.14.2
      - wcwidth==0.2.13
